### ISSUE TITLE
File listing limited

### ISSUE THREAD

**Issue by AnaRose356** [nigel/DiscordStorage#1]
When doing the ds.py -l command it seems that it's limited to 7 files. I've tested this multiple times with different files and it is the same. Not sure if it's related to this but for every command it says unclosed client session which also blocks me from using -h. Anyways here's what powershell shows at the end of the file list.

Traceback (most recent call last):
  File "ds.py", line 135, in <module>
    parseArgs(sys.argv)
  File "ds.py", line 102, in parseArgs
    print('name: ' + str(FILES[key][0]) + ' | code: ' + str(key) + ' | size: ' + GetHumanReadable(FILES[key][1]) +'')
TypeError: 'NoneType' object is not subscriptable
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x03007150>

Here's a screenshot of the list and such: https://puu.sh/zgha8.png

**Comment by nigel** [comment]
The error was a result of the program's inability to read null values from incorrectly uploaded files for whatever reason. I found nothing that indicates the num of files uploaded to be related to this error.

The new commit should fix your problem
