### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by AnaRose356** [nigel/DiscordStorage#4]
The left is the old discord storage folder from a little after the original issue I had was fixed awhile ago. I just was going to start uploading more files, but it refuses to allow me to upload or download. 
The right is a new download of discord storage that doesn't even create a config file, doesn't ask for any info, just doesn't work at all. I have the requirements all met.
![image](https://user-images.githubusercontent.com/11483055/72124378-29bb3880-332a-11ea-926d-5cda541ae233.png)

I should also add that I tried importing my original config file and deleting that file and retrying with the old discord storage folder, and neither worked. Deleting the old config file in the old folder went through asking for the bot ID and channel ID again and created a new config but trying to upload or download gets the same error as shown in the original picture.

I've tested my way up the versions and none seem to want to work anymore, the latest change of deleting the Session.py is what causes it to give me the error shown on the right in the original image. Every change made before then simply gives me:

UPLOADING: X:\Music\Foreigner_The_Definitive_Collection.7z
Channel ID doesn't exist, reconfigure the program or update config.discord
[ERROR] File upload fail

And this is with me trying multiple different channel IDs.
I should Also not I'm using python 3.6.8 64 bit
I've tested 3.6.8 32 bit and 3.7.6 32 bit to no avail.

**Comment by Drake356** [comment]
I should also add that I tried importing my original config file and deleting that file and retrying with the old discord storage folder, and neither worked. Deleting the old config file in the old folder went through asking for the bot ID and channel ID again and created a new config but trying to upload or download gets the same error as shown in the original picture.

**Comment by nigel** [comment]
From your issue description it seems like a dependency issue on one of the packages (probably discord.py). I’ll take a closer look at this issue once I get home

**Comment by nigel** [comment]
I've added back Session.py, try again to see if the error persists.

**Comment by AnaRose356** [comment]
![image](https://user-images.githubusercontent.com/11483055/72200125-061bef00-340b-11ea-9c6d-7d01f3a5f855.png)
Just keeps giving me this error which was more or less what I kept having happen while I was trying out older versions.

**Comment by AnaRose356** [comment]
Something I'm doing wrong or unknown issue?

**Comment by nigel** [comment]
I’ve identified and fixing the issue. A patch will be uploaded later. It’s a problem on how the code is using one of the dependencies

**Comment by nigel** [comment]
Try this, should fix your problem. The code broke when discord.py and aiohttp updated.

**Comment by AnaRose356** [comment]
It's working ♥ Thanks for fixing it!
