### ISSUE TITLE
Limit file uploads?

### ISSUE THREAD

**Issue by Aayush-683** [nigel/DiscordStorage#5]
Haiii! I absolutely love your project! Its SOOOO AWESOME

i had a querry

can we make it like we can setup upload limits on it and then put like 100mb upload limit to one role and 1gb limit to other?

**Comment by nigel** [comment]
Hey, I'm glad you like the project!

If you intend on having roles assigned to bots to limit their upload size, I don't see much of a general use case for this as the bot's goal is to store limitless amount of data to discord servers. I modified the discordstorage/core.py upload function below to reflect a 100MB limit. 
`

    def upload(self,inp,code):
         future = asyncio.run_coroutine_threadsafe(self.async_upload(inp,code), self.session.getLoop())
         try:
            if(os.path.getsize() > LIMIT_IN_BYTES):
                print("File size upload limit reached")
                return -1
            return future.result()
         except Exception as exc:
            print(exc)
            return -1
`

**Comment by Aayush-683** [comment]
Thanks Sooo Much For the Core.py! Can you please also tell me a way to limit specific mb to specific roles? 🤭

**Comment by Aayush-683** [comment]
also, can i just add it at the bottom of the code or somewhere else 🤔
